/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int main(int argc, char *argv[]) {
  GtkWidget *Menu_Principal;

#ifdef ENABLE_NLS
  bindtextdomain(GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset(GETTEXT_PACKAGE, "UTF-8");
  textdomain(GETTEXT_PACKAGE);
#endif

  gtk_set_locale();
  gtk_init(&argc, &argv);
  g_print("DEBUG: Starting Main... Main Window ONLY should open.\n");

  add_pixmap_directory(PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");
  add_pixmap_directory("src/"); /* Look in src for local images */
  gtk_rc_parse("style.rc");

  /*
   * Only show the main window at startup.
   */
  Menu_Principal = create_Menu_Principal();
  gtk_widget_show(Menu_Principal);

  gtk_main();
  return 0;
}
