/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Int_Ges_Mem (void);
GtkWidget* create_Log_In_Ges_Mem (void);
GtkWidget* create_Int_Adm_Mem (void);
GtkWidget* create_Int_Aj_Mem (void);
GtkWidget* create_Modifier_Membre (void);
GtkWidget* create_Rech_Mod_Mem (void);
GtkWidget* create_Rech_DEL_Mem (void);
GtkWidget* create_Supp_Mem (void);
GtkWidget* create_dem_coach_prv (void);
GtkWidget* create_Int_Membre (void);
GtkWidget* create_Error (void);
GtkWidget* create_Conf_Add_Chang (void);
GtkWidget* create_Conf_Del (void);
