/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <stdio.h>
#include <string.h>

#include "interface.h"
#include "support.h"
#include "member.h"
#include "gestion_entraineurs.h"
#include "reservation.h"


int
main (int argc, char *argv[])
{
  GtkWidget *Int_Ges_Mem;
  GtkWidget *Log_In_Ges_Mem;
  GtkWidget *Int_Adm_Mem;
  GtkWidget *Int_Aj_Mem;
  GtkWidget *Modifier_Membre;
  GtkWidget *Rech_Mod_Mem;
  GtkWidget *Rech_DEL_Mem;
  GtkWidget *Supp_Mem;
  GtkWidget *dem_coach_prv;
  GtkWidget *Int_Membre;
  GtkWidget *Error;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  /* Load modules that use in-memory arrays */
  charger_reservations();

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Int_Ges_Mem = create_Int_Ges_Mem ();
  gtk_widget_show (Int_Ges_Mem);

  gtk_main ();
  return 0;
}





