/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_admin_window (void)
{
  GtkWidget *admin_window;
  GtkWidget *fixed2;
  GtkWidget *btn_rechercher_en;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label16;
  GtkWidget *btn_ajouter_en;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label14;
  GtkWidget *btn_modifier_en;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label15;
  GtkWidget *btn_supprimer_en;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label17;
  GtkWidget *btn_retour_admin;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label21;
  GtkWidget *fixed13;
  GtkWidget *btn_voirliste_en;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image35;
  GtkWidget *label232;
  GtkWidget *label12;

  admin_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (admin_window, 800, 600);
  GTK_WIDGET_SET_FLAGS (admin_window, GTK_CAN_DEFAULT);
  gtk_window_set_title (GTK_WINDOW (admin_window), _("Interface Admin"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (admin_window), fixed2);
  gtk_widget_set_size_request (fixed2, 1144, 528);

  btn_rechercher_en = gtk_button_new ();
  gtk_widget_show (btn_rechercher_en);
  gtk_fixed_put (GTK_FIXED (fixed2), btn_rechercher_en, 312, 168);
  gtk_widget_set_size_request (btn_rechercher_en, 200, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (btn_rechercher_en), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Rechercher un entraineur"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox3), label16, FALSE, FALSE, 0);

  btn_ajouter_en = gtk_button_new ();
  gtk_widget_show (btn_ajouter_en);
  gtk_fixed_put (GTK_FIXED (fixed2), btn_ajouter_en, 312, 208);
  gtk_widget_set_size_request (btn_ajouter_en, 200, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (btn_ajouter_en), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Ajouter un entraineur\n"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox1), label14, FALSE, FALSE, 0);

  btn_modifier_en = gtk_button_new ();
  gtk_widget_show (btn_modifier_en);
  gtk_fixed_put (GTK_FIXED (fixed2), btn_modifier_en, 312, 248);
  gtk_widget_set_size_request (btn_modifier_en, 200, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (btn_modifier_en), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Modifier un entraineur\n"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox2), label15, FALSE, FALSE, 0);

  btn_supprimer_en = gtk_button_new ();
  gtk_widget_show (btn_supprimer_en);
  gtk_fixed_put (GTK_FIXED (fixed2), btn_supprimer_en, 312, 288);
  gtk_widget_set_size_request (btn_supprimer_en, 200, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (btn_supprimer_en), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Supprimer un entraineur\n"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox4), label17, FALSE, FALSE, 0);

  btn_retour_admin = gtk_button_new ();
  gtk_widget_show (btn_retour_admin);
  gtk_fixed_put (GTK_FIXED (fixed2), btn_retour_admin, 368, 384);
  gtk_widget_set_size_request (btn_retour_admin, 80, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (btn_retour_admin), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox6), label21, FALSE, FALSE, 0);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_fixed_put (GTK_FIXED (fixed2), fixed13, 296, 88);
  gtk_widget_set_size_request (fixed13, 256, 168);

  btn_voirliste_en = gtk_button_new ();
  gtk_widget_show (btn_voirliste_en);
  gtk_fixed_put (GTK_FIXED (fixed13), btn_voirliste_en, 0, 32);
  gtk_widget_set_size_request (btn_voirliste_en, 248, 32);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (btn_voirliste_en), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image35 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_box_pack_start (GTK_BOX (hbox30), image35, FALSE, FALSE, 0);

  label232 = gtk_label_new_with_mnemonic (_("Voir la liste des entraineurs"));
  gtk_widget_show (label232);
  gtk_box_pack_start (GTK_BOX (hbox30), label232, FALSE, FALSE, 0);

  label12 = gtk_label_new (_("<span weight=\"bold\" foreground=\"black\" size=\"large\">\nEspaceadministrateur\nGestion des entraineurs\n</span>"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 248, 0);
  gtk_widget_set_size_request (label12, 344, 104);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label12), 0.5, 0.56);

  g_signal_connect ((gpointer) btn_rechercher_en, "clicked",
                    G_CALLBACK (on_btn_rechercher_en_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_ajouter_en, "clicked",
                    G_CALLBACK (on_btn_ajouter_en_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_modifier_en, "clicked",
                    G_CALLBACK (on_btn_modifier_en_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_supprimer_en, "clicked",
                    G_CALLBACK (on_btn_supprimer_en_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_retour_admin, "clicked",
                    G_CALLBACK (on_btn_retour_admin_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_voirliste_en, "clicked",
                    G_CALLBACK (on_btn_voirliste_en_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (admin_window, admin_window, "admin_window");
  GLADE_HOOKUP_OBJECT (admin_window, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (admin_window, btn_rechercher_en, "btn_rechercher_en");
  GLADE_HOOKUP_OBJECT (admin_window, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (admin_window, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (admin_window, image3, "image3");
  GLADE_HOOKUP_OBJECT (admin_window, label16, "label16");
  GLADE_HOOKUP_OBJECT (admin_window, btn_ajouter_en, "btn_ajouter_en");
  GLADE_HOOKUP_OBJECT (admin_window, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (admin_window, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (admin_window, image1, "image1");
  GLADE_HOOKUP_OBJECT (admin_window, label14, "label14");
  GLADE_HOOKUP_OBJECT (admin_window, btn_modifier_en, "btn_modifier_en");
  GLADE_HOOKUP_OBJECT (admin_window, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (admin_window, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (admin_window, image2, "image2");
  GLADE_HOOKUP_OBJECT (admin_window, label15, "label15");
  GLADE_HOOKUP_OBJECT (admin_window, btn_supprimer_en, "btn_supprimer_en");
  GLADE_HOOKUP_OBJECT (admin_window, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (admin_window, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (admin_window, image4, "image4");
  GLADE_HOOKUP_OBJECT (admin_window, label17, "label17");
  GLADE_HOOKUP_OBJECT (admin_window, btn_retour_admin, "btn_retour_admin");
  GLADE_HOOKUP_OBJECT (admin_window, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (admin_window, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (admin_window, image6, "image6");
  GLADE_HOOKUP_OBJECT (admin_window, label21, "label21");
  GLADE_HOOKUP_OBJECT (admin_window, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (admin_window, btn_voirliste_en, "btn_voirliste_en");
  GLADE_HOOKUP_OBJECT (admin_window, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (admin_window, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (admin_window, image35, "image35");
  GLADE_HOOKUP_OBJECT (admin_window, label232, "label232");
  GLADE_HOOKUP_OBJECT (admin_window, label12, "label12");

  return admin_window;
}

GtkWidget*
create_gesen_window (void)
{
  GtkWidget *gesen_window;
  GtkWidget *fixed3;
  GtkWidget *btn_admin_en;
  GtkWidget *btn_entraineur_en;
  GtkWidget *btn_quitter;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label161;
  GtkWidget *label13;
  GtkWidget *label37;

  gesen_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gesen_window, 800, 600);
  GTK_WIDGET_SET_FLAGS (gesen_window, GTK_CAN_DEFAULT);
  gtk_window_set_title (GTK_WINDOW (gesen_window), _("Gestion des Entraineurs"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (gesen_window), fixed3);

  btn_admin_en = gtk_button_new_with_mnemonic (_("Administrateur"));
  gtk_widget_show (btn_admin_en);
  gtk_fixed_put (GTK_FIXED (fixed3), btn_admin_en, 184, 232);
  gtk_widget_set_size_request (btn_admin_en, 184, 56);

  btn_entraineur_en = gtk_button_new_with_mnemonic (_("Entraineur"));
  gtk_widget_show (btn_entraineur_en);
  gtk_fixed_put (GTK_FIXED (fixed3), btn_entraineur_en, 448, 232);
  gtk_widget_set_size_request (btn_entraineur_en, 176, 56);

  btn_quitter = gtk_button_new ();
  gtk_widget_show (btn_quitter);
  gtk_fixed_put (GTK_FIXED (fixed3), btn_quitter, 336, 360);
  gtk_widget_set_size_request (btn_quitter, 120, 40);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (btn_quitter), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label161 = gtk_label_new_with_mnemonic (_("Quiter"));
  gtk_widget_show (label161);
  gtk_box_pack_start (GTK_BOX (hbox22), label161, FALSE, FALSE, 0);

  label13 = gtk_label_new (_("<span weight=\"bold\" foreground=\"black\" size=\"large\">Gestion des Entraineurs</span>"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 256, 48);
  gtk_widget_set_size_request (label13, 304, 32);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label13), 0.48, 0.5);

  label37 = gtk_label_new (_("Veuiller choisir"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed3), label37, 336, 144);
  gtk_widget_set_size_request (label37, 128, 16);

  g_signal_connect ((gpointer) btn_admin_en, "clicked",
                    G_CALLBACK (on_btn_admin_en_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_entraineur_en, "clicked",
                    G_CALLBACK (on_btn_entraineur_en_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_quitter, "clicked",
                    G_CALLBACK (on_btn_quitter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gesen_window, gesen_window, "gesen_window");
  GLADE_HOOKUP_OBJECT (gesen_window, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (gesen_window, btn_admin_en, "btn_admin_en");
  GLADE_HOOKUP_OBJECT (gesen_window, btn_entraineur_en, "btn_entraineur_en");
  GLADE_HOOKUP_OBJECT (gesen_window, btn_quitter, "btn_quitter");
  GLADE_HOOKUP_OBJECT (gesen_window, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (gesen_window, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (gesen_window, image22, "image22");
  GLADE_HOOKUP_OBJECT (gesen_window, label161, "label161");
  GLADE_HOOKUP_OBJECT (gesen_window, label13, "label13");
  GLADE_HOOKUP_OBJECT (gesen_window, label37, "label37");

  return gesen_window;
}

GtkWidget*
create_modifier_window (void)
{
  GtkWidget *modifier_window;
  GtkWidget *fixed4;
  GtkWidget *entry_recherche_m;
  GtkWidget *entry_email_m;
  GtkWidget *entry_num_m;
  GtkWidget *entry_prenom_m;
  GtkWidget *entry_nom_m;
  GtkWidget *label143;
  GtkWidget *label144;
  GtkWidget *btn_annule_m;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label40;
  GtkWidget *btn_modifie;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *btn_modifier;
  GtkWidget *label_prive_m;
  GtkWidget *check_oui_m;
  GtkWidget *check_non_m;
  GtkWidget *lb_hf_m;
  GtkWidget *lb_hd_m;
  GtkWidget *lb_centres_m;
  GtkObject *spin_hd_m_adj;
  GtkWidget *spin_hd_m;
  GtkObject *spin_hf_m_adj;
  GtkWidget *spin_hf_m;
  GtkWidget *lb_jour_m;
  GtkWidget *com_centre_m;
  GtkWidget *com_jour_m;
  GtkWidget *lb_email_m;
  GtkWidget *comboboxentry1;
  GtkWidget *lb_num_m;
  GtkWidget *lb_specialite_m;
  GtkWidget *radio_homme_m;
  GSList *radio_homme_m_group = NULL;
  GtkWidget *radio_femme_m;
  GSList *radio_femme_m_group = NULL;
  GtkWidget *lb_sexe_m;
  GtkWidget *btn_recherche_m;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label51;
  GtkWidget *lb_nom_m;
  GtkWidget *lb_prenom_m;
  GtkWidget *label236;
  GtkWidget *label190;
  GtkWidget *label191;
  GtkWidget *label221;
  GtkWidget *label187;
  GtkWidget *label186;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label88;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label237;
  GtkWidget *label160;
  GtkWidget *label235;

  modifier_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (modifier_window, 800, 600);
  GTK_WIDGET_SET_FLAGS (modifier_window, GTK_CAN_DEFAULT);
  gtk_window_set_title (GTK_WINDOW (modifier_window), _("Modifier Entraineur"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (modifier_window), fixed4);
  gtk_widget_set_size_request (fixed4, 800, 800);

  entry_recherche_m = gtk_entry_new ();
  gtk_widget_show (entry_recherche_m);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_recherche_m, 272, 72);
  gtk_widget_set_size_request (entry_recherche_m, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_recherche_m), 8226);

  entry_email_m = gtk_entry_new ();
  gtk_widget_show (entry_email_m);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_email_m, 384, 360);
  gtk_widget_set_size_request (entry_email_m, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_email_m), 8226);

  entry_num_m = gtk_entry_new ();
  gtk_widget_show (entry_num_m);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_num_m, 384, 288);
  gtk_widget_set_size_request (entry_num_m, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_num_m), 8226);

  entry_prenom_m = gtk_entry_new ();
  gtk_widget_show (entry_prenom_m);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_prenom_m, 384, 216);
  gtk_widget_set_size_request (entry_prenom_m, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom_m), 8226);

  entry_nom_m = gtk_entry_new ();
  gtk_widget_show (entry_nom_m);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_nom_m, 384, 176);
  gtk_widget_set_size_request (entry_nom_m, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom_m), 8226);

  label143 = gtk_label_new ("");
  gtk_widget_show (label143);
  gtk_fixed_put (GTK_FIXED (fixed4), label143, 0, 0);
  gtk_widget_set_size_request (label143, 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label143), 0, 0.5);

  label144 = gtk_label_new ("");
  gtk_widget_show (label144);
  gtk_fixed_put (GTK_FIXED (fixed4), label144, 0, 0);
  gtk_widget_set_size_request (label144, 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label144), 0, 0.5);

  btn_annule_m = gtk_button_new ();
  gtk_widget_show (btn_annule_m);
  gtk_fixed_put (GTK_FIXED (fixed4), btn_annule_m, 192, 688);
  gtk_widget_set_size_request (btn_annule_m, 176, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (btn_annule_m), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox9), label40, FALSE, FALSE, 0);

  btn_modifie = gtk_button_new ();
  gtk_widget_show (btn_modifie);
  gtk_fixed_put (GTK_FIXED (fixed4), btn_modifie, 400, 688);
  gtk_widget_set_size_request (btn_modifie, 184, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (btn_modifie), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  btn_modifier = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (btn_modifier);
  gtk_box_pack_start (GTK_BOX (hbox7), btn_modifier, FALSE, FALSE, 0);

  label_prive_m = gtk_label_new (_("label222"));
  gtk_widget_show (label_prive_m);
  gtk_fixed_put (GTK_FIXED (fixed4), label_prive_m, 192, 640);
  gtk_widget_set_size_request (label_prive_m, 57, 17);

  check_oui_m = gtk_check_button_new_with_mnemonic (_("OUI "));
  gtk_widget_show (check_oui_m);
  gtk_fixed_put (GTK_FIXED (fixed4), check_oui_m, 400, 632);
  gtk_widget_set_size_request (check_oui_m, 118, 24);

  check_non_m = gtk_check_button_new_with_mnemonic (_("NON"));
  gtk_widget_show (check_non_m);
  gtk_fixed_put (GTK_FIXED (fixed4), check_non_m, 488, 632);
  gtk_widget_set_size_request (check_non_m, 118, 24);

  lb_hf_m = gtk_label_new (_("label193"));
  gtk_widget_show (lb_hf_m);
  gtk_fixed_put (GTK_FIXED (fixed4), lb_hf_m, 192, 600);
  gtk_widget_set_size_request (lb_hf_m, 57, 17);

  lb_hd_m = gtk_label_new (_("label192"));
  gtk_widget_show (lb_hd_m);
  gtk_fixed_put (GTK_FIXED (fixed4), lb_hd_m, 192, 568);
  gtk_widget_set_size_request (lb_hd_m, 57, 17);

  lb_centres_m = gtk_label_new (_("label188"));
  gtk_widget_show (lb_centres_m);
  gtk_fixed_put (GTK_FIXED (fixed4), lb_centres_m, 192, 480);
  gtk_widget_set_size_request (lb_centres_m, 57, 17);

  spin_hd_m_adj = gtk_adjustment_new (0, 0, 100, 1, 0, 0);
  spin_hd_m = gtk_spin_button_new (GTK_ADJUSTMENT (spin_hd_m_adj), 1, 0);
  gtk_widget_show (spin_hd_m);
  gtk_fixed_put (GTK_FIXED (fixed4), spin_hd_m, 400, 560);
  gtk_widget_set_size_request (spin_hd_m, 60, 27);

  spin_hf_m_adj = gtk_adjustment_new (3, 0, 100, 1, 0, 0);
  spin_hf_m = gtk_spin_button_new (GTK_ADJUSTMENT (spin_hf_m_adj), 1, 0);
  gtk_widget_show (spin_hf_m);
  gtk_fixed_put (GTK_FIXED (fixed4), spin_hf_m, 400, 592);
  gtk_widget_set_size_request (spin_hf_m, 60, 27);

  lb_jour_m = gtk_label_new (_("label189"));
  gtk_widget_show (lb_jour_m);
  gtk_fixed_put (GTK_FIXED (fixed4), lb_jour_m, 192, 520);
  gtk_widget_set_size_request (lb_jour_m, 57, 17);

  com_centre_m = gtk_combo_box_entry_new_text ();
  gtk_widget_show (com_centre_m);
  gtk_fixed_put (GTK_FIXED (fixed4), com_centre_m, 400, 472);
  gtk_widget_set_size_request (com_centre_m, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_centre_m), _("Centre 1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_centre_m), _("centre 2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_centre_m), _("centre 3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_centre_m), _("centre 4"));

  com_jour_m = gtk_combo_box_entry_new_text ();
  gtk_widget_show (com_jour_m);
  gtk_fixed_put (GTK_FIXED (fixed4), com_jour_m, 400, 512);
  gtk_widget_set_size_request (com_jour_m, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_m), _("Lundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_m), _("Mardi "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_m), _("Mercredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_m), _("Jeudi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_m), _("Vendredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_m), _("Samdi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_m), _("Dimanche"));

  lb_email_m = gtk_label_new (_("label182"));
  gtk_widget_show (lb_email_m);
  gtk_fixed_put (GTK_FIXED (fixed4), lb_email_m, 192, 368);
  gtk_widget_set_size_request (lb_email_m, 57, 17);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed4), comboboxentry1, 384, 328);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Cardio Training"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Yoga"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Box"));

  lb_num_m = gtk_label_new (_("label180"));
  gtk_widget_show (lb_num_m);
  gtk_fixed_put (GTK_FIXED (fixed4), lb_num_m, 192, 296);
  gtk_widget_set_size_request (lb_num_m, 57, 17);

  lb_specialite_m = gtk_label_new (_("label181"));
  gtk_widget_show (lb_specialite_m);
  gtk_fixed_put (GTK_FIXED (fixed4), lb_specialite_m, 192, 336);
  gtk_widget_set_size_request (lb_specialite_m, 57, 17);

  radio_homme_m = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radio_homme_m);
  gtk_fixed_put (GTK_FIXED (fixed4), radio_homme_m, 384, 256);
  gtk_widget_set_size_request (radio_homme_m, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_homme_m), radio_homme_m_group);
  radio_homme_m_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_homme_m));

  radio_femme_m = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radio_femme_m);
  gtk_fixed_put (GTK_FIXED (fixed4), radio_femme_m, 496, 256);
  gtk_widget_set_size_request (radio_femme_m, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_femme_m), radio_femme_m_group);
  radio_femme_m_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_femme_m));

  lb_sexe_m = gtk_label_new (_("label184"));
  gtk_widget_show (lb_sexe_m);
  gtk_fixed_put (GTK_FIXED (fixed4), lb_sexe_m, 192, 264);
  gtk_widget_set_size_request (lb_sexe_m, 57, 17);

  btn_recherche_m = gtk_button_new ();
  gtk_widget_show (btn_recherche_m);
  gtk_fixed_put (GTK_FIXED (fixed4), btn_recherche_m, 488, 72);
  gtk_widget_set_size_request (btn_recherche_m, 120, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (btn_recherche_m), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("rechercher"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox12), label51, FALSE, FALSE, 0);

  lb_nom_m = gtk_label_new (_("label178"));
  gtk_widget_show (lb_nom_m);
  gtk_fixed_put (GTK_FIXED (fixed4), lb_nom_m, 192, 184);
  gtk_widget_set_size_request (lb_nom_m, 57, 17);

  lb_prenom_m = gtk_label_new (_("label179"));
  gtk_widget_show (lb_prenom_m);
  gtk_fixed_put (GTK_FIXED (fixed4), lb_prenom_m, 192, 224);
  gtk_widget_set_size_request (lb_prenom_m, 57, 17);

  label236 = gtk_label_new (_("<span weight=\"bold\" foreground=\"black\" size=\"large\">\nDisponibilit\303\251 de l'entraineurs\n</span>"));
  gtk_widget_show (label236);
  gtk_fixed_put (GTK_FIXED (fixed4), label236, 24, 400);
  gtk_widget_set_size_request (label236, 256, 56);
  gtk_label_set_use_markup (GTK_LABEL (label236), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label236), 0.5, 0.56);

  label190 = gtk_label_new (_("<b>Heure de d\303\251but :</b>"));
  gtk_widget_show (label190);
  gtk_fixed_put (GTK_FIXED (fixed4), label190, 40, 568);
  gtk_widget_set_size_request (label190, 136, 16);
  gtk_label_set_use_markup (GTK_LABEL (label190), TRUE);

  label191 = gtk_label_new (_("<b>Heure fin :</b>"));
  gtk_widget_show (label191);
  gtk_fixed_put (GTK_FIXED (fixed4), label191, 40, 600);
  gtk_widget_set_size_request (label191, 88, 16);
  gtk_label_set_use_markup (GTK_LABEL (label191), TRUE);

  label221 = gtk_label_new (_("<b>Priv\303\251 :</b>"));
  gtk_widget_show (label221);
  gtk_fixed_put (GTK_FIXED (fixed4), label221, 48, 640);
  gtk_widget_set_size_request (label221, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label221), TRUE);

  label187 = gtk_label_new (_("<b>Le Jour :</b>"));
  gtk_widget_show (label187);
  gtk_fixed_put (GTK_FIXED (fixed4), label187, 32, 520);
  gtk_widget_set_size_request (label187, 88, 16);
  gtk_label_set_use_markup (GTK_LABEL (label187), TRUE);

  label186 = gtk_label_new (_("<b>Au centre sportif :</b>"));
  gtk_widget_show (label186);
  gtk_fixed_put (GTK_FIXED (fixed4), label186, 40, 480);
  gtk_widget_set_size_request (label186, 136, 24);
  gtk_label_set_use_markup (GTK_LABEL (label186), TRUE);

  label24 = gtk_label_new (_("<b>ID entraineur \303\240 modifier</b>"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed4), label24, 48, 64);
  gtk_widget_set_size_request (label24, 216, 48);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  label25 = gtk_label_new (_("<b>Nom</b>"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 48, 184);
  gtk_widget_set_size_request (label25, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  label88 = gtk_label_new (_("<b>Pr\303\251nom</b>"));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed4), label88, 48, 224);
  gtk_widget_set_size_request (label88, 64, 24);
  gtk_label_set_use_markup (GTK_LABEL (label88), TRUE);

  label27 = gtk_label_new (_("<b>Sexe</b>"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed4), label27, 48, 256);
  gtk_widget_set_size_request (label27, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  label28 = gtk_label_new (_("<b>Num\303\251ro t\303\251l</b>"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed4), label28, 32, 296);
  gtk_widget_set_size_request (label28, 112, 16);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  label29 = gtk_label_new (_("<b>Sp\303\251cialit\303\251</b>"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed4), label29, 48, 336);
  gtk_widget_set_size_request (label29, 80, 16);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  label30 = gtk_label_new (_("<b>Adresse Email</b>"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed4), label30, 40, 368);
  gtk_widget_set_size_request (label30, 120, 16);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  label237 = gtk_label_new (_("<span weight=\"bold\" foreground=\"black\" size=\"large\">R\303\251sultats de recherche</span>"));
  gtk_widget_show (label237);
  gtk_fixed_put (GTK_FIXED (fixed4), label237, 8, 136);
  gtk_widget_set_size_request (label237, 256, 24);
  gtk_label_set_use_markup (GTK_LABEL (label237), TRUE);

  label160 = gtk_label_new (_("<span weight=\"bold\" foreground=\"black\" size=\"large\">Modification</span>"));
  gtk_widget_show (label160);
  gtk_fixed_put (GTK_FIXED (fixed4), label160, 392, 136);
  gtk_widget_set_size_request (label160, 168, 24);
  gtk_label_set_use_markup (GTK_LABEL (label160), TRUE);

  label235 = gtk_label_new (_("<span weight=\"bold\" foreground=\"black\" size=\"large\">\nModification des entraineurs\n</span>"));
  gtk_widget_show (label235);
  gtk_fixed_put (GTK_FIXED (fixed4), label235, 256, 0);
  gtk_widget_set_size_request (label235, 296, 48);
  gtk_label_set_use_markup (GTK_LABEL (label235), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label235), 0.5, 0.56);

  g_signal_connect ((gpointer) btn_annule_m, "clicked",
                    G_CALLBACK (on_btn_annule_m_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_modifie, "clicked",
                    G_CALLBACK (on_btn_modifie_clicked),
                    NULL);
  g_signal_connect ((gpointer) check_oui_m, "toggled",
                    G_CALLBACK (on_check_oui_m_toggled),
                    NULL);
  g_signal_connect ((gpointer) check_non_m, "toggled",
                    G_CALLBACK (on_check_non_m_toggled),
                    NULL);
  g_signal_connect ((gpointer) radio_homme_m, "toggled",
                    G_CALLBACK (on_radio_homme_m_toggled),
                    NULL);
  g_signal_connect ((gpointer) radio_femme_m, "toggled",
                    G_CALLBACK (on_radio_femme_m_toggled),
                    NULL);
  g_signal_connect ((gpointer) btn_recherche_m, "clicked",
                    G_CALLBACK (on_btn_recherche_m_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_window, modifier_window, "modifier_window");
  GLADE_HOOKUP_OBJECT (modifier_window, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (modifier_window, entry_recherche_m, "entry_recherche_m");
  GLADE_HOOKUP_OBJECT (modifier_window, entry_email_m, "entry_email_m");
  GLADE_HOOKUP_OBJECT (modifier_window, entry_num_m, "entry_num_m");
  GLADE_HOOKUP_OBJECT (modifier_window, entry_prenom_m, "entry_prenom_m");
  GLADE_HOOKUP_OBJECT (modifier_window, entry_nom_m, "entry_nom_m");
  GLADE_HOOKUP_OBJECT (modifier_window, label143, "label143");
  GLADE_HOOKUP_OBJECT (modifier_window, label144, "label144");
  GLADE_HOOKUP_OBJECT (modifier_window, btn_annule_m, "btn_annule_m");
  GLADE_HOOKUP_OBJECT (modifier_window, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (modifier_window, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (modifier_window, image9, "image9");
  GLADE_HOOKUP_OBJECT (modifier_window, label40, "label40");
  GLADE_HOOKUP_OBJECT (modifier_window, btn_modifie, "btn_modifie");
  GLADE_HOOKUP_OBJECT (modifier_window, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (modifier_window, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (modifier_window, image7, "image7");
  GLADE_HOOKUP_OBJECT (modifier_window, btn_modifier, "btn_modifier");
  GLADE_HOOKUP_OBJECT (modifier_window, label_prive_m, "label_prive_m");
  GLADE_HOOKUP_OBJECT (modifier_window, check_oui_m, "check_oui_m");
  GLADE_HOOKUP_OBJECT (modifier_window, check_non_m, "check_non_m");
  GLADE_HOOKUP_OBJECT (modifier_window, lb_hf_m, "lb_hf_m");
  GLADE_HOOKUP_OBJECT (modifier_window, lb_hd_m, "lb_hd_m");
  GLADE_HOOKUP_OBJECT (modifier_window, lb_centres_m, "lb_centres_m");
  GLADE_HOOKUP_OBJECT (modifier_window, spin_hd_m, "spin_hd_m");
  GLADE_HOOKUP_OBJECT (modifier_window, spin_hf_m, "spin_hf_m");
  GLADE_HOOKUP_OBJECT (modifier_window, lb_jour_m, "lb_jour_m");
  GLADE_HOOKUP_OBJECT (modifier_window, com_centre_m, "com_centre_m");
  GLADE_HOOKUP_OBJECT (modifier_window, com_jour_m, "com_jour_m");
  GLADE_HOOKUP_OBJECT (modifier_window, lb_email_m, "lb_email_m");
  GLADE_HOOKUP_OBJECT (modifier_window, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (modifier_window, lb_num_m, "lb_num_m");
  GLADE_HOOKUP_OBJECT (modifier_window, lb_specialite_m, "lb_specialite_m");
  GLADE_HOOKUP_OBJECT (modifier_window, radio_homme_m, "radio_homme_m");
  GLADE_HOOKUP_OBJECT (modifier_window, radio_femme_m, "radio_femme_m");
  GLADE_HOOKUP_OBJECT (modifier_window, lb_sexe_m, "lb_sexe_m");
  GLADE_HOOKUP_OBJECT (modifier_window, btn_recherche_m, "btn_recherche_m");
  GLADE_HOOKUP_OBJECT (modifier_window, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (modifier_window, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (modifier_window, image12, "image12");
  GLADE_HOOKUP_OBJECT (modifier_window, label51, "label51");
  GLADE_HOOKUP_OBJECT (modifier_window, lb_nom_m, "lb_nom_m");
  GLADE_HOOKUP_OBJECT (modifier_window, lb_prenom_m, "lb_prenom_m");
  GLADE_HOOKUP_OBJECT (modifier_window, label236, "label236");
  GLADE_HOOKUP_OBJECT (modifier_window, label190, "label190");
  GLADE_HOOKUP_OBJECT (modifier_window, label191, "label191");
  GLADE_HOOKUP_OBJECT (modifier_window, label221, "label221");
  GLADE_HOOKUP_OBJECT (modifier_window, label187, "label187");
  GLADE_HOOKUP_OBJECT (modifier_window, label186, "label186");
  GLADE_HOOKUP_OBJECT (modifier_window, label24, "label24");
  GLADE_HOOKUP_OBJECT (modifier_window, label25, "label25");
  GLADE_HOOKUP_OBJECT (modifier_window, label88, "label88");
  GLADE_HOOKUP_OBJECT (modifier_window, label27, "label27");
  GLADE_HOOKUP_OBJECT (modifier_window, label28, "label28");
  GLADE_HOOKUP_OBJECT (modifier_window, label29, "label29");
  GLADE_HOOKUP_OBJECT (modifier_window, label30, "label30");
  GLADE_HOOKUP_OBJECT (modifier_window, label237, "label237");
  GLADE_HOOKUP_OBJECT (modifier_window, label160, "label160");
  GLADE_HOOKUP_OBJECT (modifier_window, label235, "label235");

  return modifier_window;
}

GtkWidget*
create_Login_admin (void)
{
  GtkWidget *Login_admin;
  GtkWidget *fixed5;
  GtkWidget *entry_id_ad;
  GtkWidget *entry_mdp_ad;
  GtkWidget *btn_annule_cnxad;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label43;
  GtkWidget *btn_cnxad;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label44;
  GtkWidget *label33;
  GtkWidget *label32;
  GtkWidget *label226;
  GtkWidget *image28;
  GtkWidget *label34;

  Login_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Login_admin, 800, 600);
  GTK_WIDGET_SET_FLAGS (Login_admin, GTK_CAN_DEFAULT);
  gtk_window_set_title (GTK_WINDOW (Login_admin), _("se connecter Admin"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Login_admin), fixed5);

  entry_id_ad = gtk_entry_new ();
  gtk_widget_show (entry_id_ad);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_id_ad, 400, 176);
  gtk_widget_set_size_request (entry_id_ad, 224, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_ad), 8226);

  entry_mdp_ad = gtk_entry_new ();
  gtk_widget_show (entry_mdp_ad);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_mdp_ad, 400, 240);
  gtk_widget_set_size_request (entry_mdp_ad, 224, 32);
  gtk_entry_set_visibility (GTK_ENTRY (entry_mdp_ad), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mdp_ad), 8226);

  btn_annule_cnxad = gtk_button_new ();
  gtk_widget_show (btn_annule_cnxad);
  gtk_fixed_put (GTK_FIXED (fixed5), btn_annule_cnxad, 160, 368);
  gtk_widget_set_size_request (btn_annule_cnxad, 216, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (btn_annule_cnxad), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox10), label43, FALSE, FALSE, 0);

  btn_cnxad = gtk_button_new ();
  gtk_widget_show (btn_cnxad);
  gtk_fixed_put (GTK_FIXED (fixed5), btn_cnxad, 456, 368);
  gtk_widget_set_size_request (btn_cnxad, 216, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (btn_cnxad), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Se connecter"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox11), label44, FALSE, FALSE, 0);

  label33 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed5), label33, 248, 248);
  gtk_widget_set_size_request (label33, 120, 16);

  label32 = gtk_label_new (_("Id Administrateur"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed5), label32, 240, 176);
  gtk_widget_set_size_request (label32, 144, 24);

  label226 = gtk_label_new (_("Bonjour admin              "));
  gtk_widget_show (label226);
  gtk_fixed_put (GTK_FIXED (fixed5), label226, 320, 96);
  gtk_widget_set_size_request (label226, 168, 32);

  image28 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_fixed_put (GTK_FIXED (fixed5), image28, 448, 88);
  gtk_widget_set_size_request (image28, 48, 48);

  label34 = gtk_label_new (_("<span weight=\"bold\" foreground=\"black\" size=\"large\">Informations de connexion</span>"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed5), label34, 264, 32);
  gtk_widget_set_size_request (label34, 280, 40);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  g_signal_connect ((gpointer) btn_annule_cnxad, "clicked",
                    G_CALLBACK (on_btn_annule_cnxad_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_cnxad, "clicked",
                    G_CALLBACK (on_btn_cnxad_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Login_admin, Login_admin, "Login_admin");
  GLADE_HOOKUP_OBJECT (Login_admin, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Login_admin, entry_id_ad, "entry_id_ad");
  GLADE_HOOKUP_OBJECT (Login_admin, entry_mdp_ad, "entry_mdp_ad");
  GLADE_HOOKUP_OBJECT (Login_admin, btn_annule_cnxad, "btn_annule_cnxad");
  GLADE_HOOKUP_OBJECT (Login_admin, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Login_admin, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Login_admin, image10, "image10");
  GLADE_HOOKUP_OBJECT (Login_admin, label43, "label43");
  GLADE_HOOKUP_OBJECT (Login_admin, btn_cnxad, "btn_cnxad");
  GLADE_HOOKUP_OBJECT (Login_admin, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Login_admin, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Login_admin, image11, "image11");
  GLADE_HOOKUP_OBJECT (Login_admin, label44, "label44");
  GLADE_HOOKUP_OBJECT (Login_admin, label33, "label33");
  GLADE_HOOKUP_OBJECT (Login_admin, label32, "label32");
  GLADE_HOOKUP_OBJECT (Login_admin, label226, "label226");
  GLADE_HOOKUP_OBJECT (Login_admin, image28, "image28");
  GLADE_HOOKUP_OBJECT (Login_admin, label34, "label34");

  return Login_admin;
}

GtkWidget*
create_recherche_window (void)
{
  GtkWidget *recherche_window;
  GtkWidget *fixed6;
  GtkWidget *entryID_En_r;
  GtkWidget *label38;
  GtkWidget *btn_recherchere;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label39;
  GtkWidget *label75;
  GtkWidget *label78;
  GtkWidget *label79;
  GtkWidget *label213;
  GtkWidget *label214;
  GtkWidget *label80;
  GtkWidget *label212;
  GtkWidget *label76;
  GtkWidget *label50;
  GtkWidget *label215;
  GtkWidget *label216;
  GtkWidget *label224;
  GtkWidget *btn_retour_rech;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label82;
  GtkWidget *label_jour_r;
  GtkWidget *label_hd_r;
  GtkWidget *label_p_r;
  GtkWidget *label_hf_r;
  GtkWidget *label_centre_r;
  GtkWidget *lab_email_r;
  GtkWidget *lab_specialite_r;
  GtkWidget *lab_num_r;
  GtkWidget *lab_sexe_r;
  GtkWidget *lab_prenom_r;
  GtkWidget *lab_nom_r;
  GtkWidget *label35;

  recherche_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (recherche_window, 800, 650);
  GTK_WIDGET_SET_FLAGS (recherche_window, GTK_CAN_DEFAULT);
  gtk_window_set_title (GTK_WINDOW (recherche_window), _("Rechercher un entraineur"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (recherche_window), fixed6);
  gtk_widget_set_size_request (fixed6, 800, 800);

  entryID_En_r = gtk_entry_new ();
  gtk_widget_show (entryID_En_r);
  gtk_fixed_put (GTK_FIXED (fixed6), entryID_En_r, 384, 80);
  gtk_widget_set_size_request (entryID_En_r, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryID_En_r), 8226);

  label38 = gtk_label_new (_("ID Entraineur"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed6), label38, 240, 80);
  gtk_widget_set_size_request (label38, 112, 24);

  btn_recherchere = gtk_button_new ();
  gtk_widget_show (btn_recherchere);
  gtk_fixed_put (GTK_FIXED (fixed6), btn_recherchere, 312, 144);
  gtk_widget_set_size_request (btn_recherchere, 176, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (btn_recherchere), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("rechercher"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox8), label39, FALSE, FALSE, 0);

  label75 = gtk_label_new (_("<b>Le resultat de recherche :</b>"));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed6), label75, 136, 200);
  gtk_widget_set_size_request (label75, 224, 16);
  gtk_label_set_use_markup (GTK_LABEL (label75), TRUE);

  label78 = gtk_label_new (_("Numero T\303\251l :"));
  gtk_widget_show (label78);
  gtk_fixed_put (GTK_FIXED (fixed6), label78, 272, 328);
  gtk_widget_set_size_request (label78, 104, 24);

  label79 = gtk_label_new (_("Sp\303\251cialit\303\251 :\n"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed6), label79, 280, 360);
  gtk_widget_set_size_request (label79, 88, 16);

  label213 = gtk_label_new (_("Centre sportis :"));
  gtk_widget_show (label213);
  gtk_fixed_put (GTK_FIXED (fixed6), label213, 264, 424);
  gtk_widget_set_size_request (label213, 128, 24);

  label214 = gtk_label_new (_("Jour :"));
  gtk_widget_show (label214);
  gtk_fixed_put (GTK_FIXED (fixed6), label214, 288, 464);
  gtk_widget_set_size_request (label214, 57, 17);

  label80 = gtk_label_new (_("Adresse Email :"));
  gtk_widget_show (label80);
  gtk_fixed_put (GTK_FIXED (fixed6), label80, 272, 392);
  gtk_widget_set_size_request (label80, 104, 16);

  label212 = gtk_label_new (_("Sexe :"));
  gtk_widget_show (label212);
  gtk_fixed_put (GTK_FIXED (fixed6), label212, 288, 304);
  gtk_widget_set_size_request (label212, 57, 17);

  label76 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed6), label76, 288, 272);
  gtk_widget_set_size_request (label76, 56, 16);

  label50 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed6), label50, 288, 240);
  gtk_widget_set_size_request (label50, 49, 17);

  label215 = gtk_label_new (_("Heure d\303\251but :"));
  gtk_widget_show (label215);
  gtk_fixed_put (GTK_FIXED (fixed6), label215, 272, 496);
  gtk_widget_set_size_request (label215, 112, 16);

  label216 = gtk_label_new (_("Heure fin :"));
  gtk_widget_show (label216);
  gtk_fixed_put (GTK_FIXED (fixed6), label216, 288, 520);
  gtk_widget_set_size_request (label216, 80, 16);

  label224 = gtk_label_new (_("Priv\303\251 :"));
  gtk_widget_show (label224);
  gtk_fixed_put (GTK_FIXED (fixed6), label224, 296, 552);
  gtk_widget_set_size_request (label224, 57, 17);

  btn_retour_rech = gtk_button_new ();
  gtk_widget_show (btn_retour_rech);
  gtk_fixed_put (GTK_FIXED (fixed6), btn_retour_rech, 64, 592);
  gtk_widget_set_size_request (btn_retour_rech, 184, 32);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (btn_retour_rech), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label82 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label82);
  gtk_box_pack_start (GTK_BOX (hbox15), label82, FALSE, FALSE, 0);

  label_jour_r = gtk_label_new (_("label218"));
  gtk_widget_show (label_jour_r);
  gtk_fixed_put (GTK_FIXED (fixed6), label_jour_r, 488, 464);
  gtk_widget_set_size_request (label_jour_r, 88, 16);

  label_hd_r = gtk_label_new (_("label219"));
  gtk_widget_show (label_hd_r);
  gtk_fixed_put (GTK_FIXED (fixed6), label_hd_r, 504, 496);
  gtk_widget_set_size_request (label_hd_r, 57, 17);

  label_p_r = gtk_label_new (_("label225"));
  gtk_widget_show (label_p_r);
  gtk_fixed_put (GTK_FIXED (fixed6), label_p_r, 504, 552);
  gtk_widget_set_size_request (label_p_r, 57, 17);

  label_hf_r = gtk_label_new (_("label220"));
  gtk_widget_show (label_hf_r);
  gtk_fixed_put (GTK_FIXED (fixed6), label_hf_r, 504, 520);
  gtk_widget_set_size_request (label_hf_r, 57, 17);

  label_centre_r = gtk_label_new (_("label217"));
  gtk_widget_show (label_centre_r);
  gtk_fixed_put (GTK_FIXED (fixed6), label_centre_r, 504, 424);
  gtk_widget_set_size_request (label_centre_r, 57, 17);

  lab_email_r = gtk_label_new (_("label209"));
  gtk_widget_show (lab_email_r);
  gtk_fixed_put (GTK_FIXED (fixed6), lab_email_r, 504, 392);
  gtk_widget_set_size_request (lab_email_r, 57, 17);

  lab_specialite_r = gtk_label_new (_("label208"));
  gtk_widget_show (lab_specialite_r);
  gtk_fixed_put (GTK_FIXED (fixed6), lab_specialite_r, 504, 360);
  gtk_widget_set_size_request (lab_specialite_r, 57, 17);

  lab_num_r = gtk_label_new (_("label207"));
  gtk_widget_show (lab_num_r);
  gtk_fixed_put (GTK_FIXED (fixed6), lab_num_r, 504, 328);
  gtk_widget_set_size_request (lab_num_r, 57, 17);

  lab_sexe_r = gtk_label_new (_("label206"));
  gtk_widget_show (lab_sexe_r);
  gtk_fixed_put (GTK_FIXED (fixed6), lab_sexe_r, 504, 304);
  gtk_widget_set_size_request (lab_sexe_r, 57, 17);

  lab_prenom_r = gtk_label_new (_("label205"));
  gtk_widget_show (lab_prenom_r);
  gtk_fixed_put (GTK_FIXED (fixed6), lab_prenom_r, 488, 272);
  gtk_widget_set_size_request (lab_prenom_r, 96, 16);

  lab_nom_r = gtk_label_new (_("label204"));
  gtk_widget_show (lab_nom_r);
  gtk_fixed_put (GTK_FIXED (fixed6), lab_nom_r, 496, 240);
  gtk_widget_set_size_request (lab_nom_r, 72, 24);

  label35 = gtk_label_new (_("<span weight=\"bold\" foreground=\"black\" size=\"large\">Rechercher un  entraineur</span>"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed6), label35, 280, 24);
  gtk_widget_set_size_request (label35, 272, 24);
  gtk_label_set_use_markup (GTK_LABEL (label35), TRUE);

  g_signal_connect ((gpointer) btn_recherchere, "clicked",
                    G_CALLBACK (on_btn_recherchere_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_retour_rech, "clicked",
                    G_CALLBACK (on_btn_retour_rech_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (recherche_window, recherche_window, "recherche_window");
  GLADE_HOOKUP_OBJECT (recherche_window, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (recherche_window, entryID_En_r, "entryID_En_r");
  GLADE_HOOKUP_OBJECT (recherche_window, label38, "label38");
  GLADE_HOOKUP_OBJECT (recherche_window, btn_recherchere, "btn_recherchere");
  GLADE_HOOKUP_OBJECT (recherche_window, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (recherche_window, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (recherche_window, image8, "image8");
  GLADE_HOOKUP_OBJECT (recherche_window, label39, "label39");
  GLADE_HOOKUP_OBJECT (recherche_window, label75, "label75");
  GLADE_HOOKUP_OBJECT (recherche_window, label78, "label78");
  GLADE_HOOKUP_OBJECT (recherche_window, label79, "label79");
  GLADE_HOOKUP_OBJECT (recherche_window, label213, "label213");
  GLADE_HOOKUP_OBJECT (recherche_window, label214, "label214");
  GLADE_HOOKUP_OBJECT (recherche_window, label80, "label80");
  GLADE_HOOKUP_OBJECT (recherche_window, label212, "label212");
  GLADE_HOOKUP_OBJECT (recherche_window, label76, "label76");
  GLADE_HOOKUP_OBJECT (recherche_window, label50, "label50");
  GLADE_HOOKUP_OBJECT (recherche_window, label215, "label215");
  GLADE_HOOKUP_OBJECT (recherche_window, label216, "label216");
  GLADE_HOOKUP_OBJECT (recherche_window, label224, "label224");
  GLADE_HOOKUP_OBJECT (recherche_window, btn_retour_rech, "btn_retour_rech");
  GLADE_HOOKUP_OBJECT (recherche_window, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (recherche_window, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (recherche_window, image15, "image15");
  GLADE_HOOKUP_OBJECT (recherche_window, label82, "label82");
  GLADE_HOOKUP_OBJECT (recherche_window, label_jour_r, "label_jour_r");
  GLADE_HOOKUP_OBJECT (recherche_window, label_hd_r, "label_hd_r");
  GLADE_HOOKUP_OBJECT (recherche_window, label_p_r, "label_p_r");
  GLADE_HOOKUP_OBJECT (recherche_window, label_hf_r, "label_hf_r");
  GLADE_HOOKUP_OBJECT (recherche_window, label_centre_r, "label_centre_r");
  GLADE_HOOKUP_OBJECT (recherche_window, lab_email_r, "lab_email_r");
  GLADE_HOOKUP_OBJECT (recherche_window, lab_specialite_r, "lab_specialite_r");
  GLADE_HOOKUP_OBJECT (recherche_window, lab_num_r, "lab_num_r");
  GLADE_HOOKUP_OBJECT (recherche_window, lab_sexe_r, "lab_sexe_r");
  GLADE_HOOKUP_OBJECT (recherche_window, lab_prenom_r, "lab_prenom_r");
  GLADE_HOOKUP_OBJECT (recherche_window, lab_nom_r, "lab_nom_r");
  GLADE_HOOKUP_OBJECT (recherche_window, label35, "label35");

  return recherche_window;
}

GtkWidget*
create_inscription_window (void)
{
  GtkWidget *inscription_window;
  GtkWidget *fixed8;
  GtkObject *spin_hd_ins_adj;
  GtkWidget *spin_hd_ins;
  GtkObject *spin_ha_ins_adj;
  GtkWidget *spin_ha_ins;
  GtkWidget *image29;
  GtkWidget *btn_annule_inscrit;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label74;
  GtkWidget *btn_inscrit;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label73;
  GtkWidget *alignment41;
  GtkWidget *com_jour_ins;
  GtkWidget *alignment44;
  GtkWidget *com_choix_eq_ins;
  GtkWidget *label67;
  GtkWidget *label72;
  GtkWidget *label198;
  GtkWidget *label201;
  GtkWidget *label202;
  GtkWidget *label203;
  GtkWidget *label129;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview_cours;
  GtkWidget *alignment45;
  GtkWidget *com_cours_ins;

  inscription_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (inscription_window, 800, 700);
  gtk_window_set_title (GTK_WINDOW (inscription_window), _("Inscription Entraineur"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (inscription_window), fixed8);
  gtk_widget_set_size_request (fixed8, 800, 600);
  GTK_WIDGET_SET_FLAGS (fixed8, GTK_CAN_DEFAULT);

  spin_hd_ins_adj = gtk_adjustment_new (0, 0, 100, 1, 0, 0);
  spin_hd_ins = gtk_spin_button_new (GTK_ADJUSTMENT (spin_hd_ins_adj), 1, 0);
  gtk_widget_show (spin_hd_ins);
  gtk_fixed_put (GTK_FIXED (fixed8), spin_hd_ins, 360, 536);
  gtk_widget_set_size_request (spin_hd_ins, 60, 27);

  spin_ha_ins_adj = gtk_adjustment_new (0, 0, 100, 1, 0, 0);
  spin_ha_ins = gtk_spin_button_new (GTK_ADJUSTMENT (spin_ha_ins_adj), 1, 0);
  gtk_widget_show (spin_ha_ins);
  gtk_fixed_put (GTK_FIXED (fixed8), spin_ha_ins, 448, 536);
  gtk_widget_set_size_request (spin_ha_ins, 60, 27);

  image29 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_fixed_put (GTK_FIXED (fixed8), image29, 560, 88);
  gtk_widget_set_size_request (image29, 40, 24);

  btn_annule_inscrit = gtk_button_new ();
  gtk_widget_show (btn_annule_inscrit);
  gtk_fixed_put (GTK_FIXED (fixed8), btn_annule_inscrit, 256, 600);
  gtk_widget_set_size_request (btn_annule_inscrit, 104, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (btn_annule_inscrit), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label74 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label74);
  gtk_box_pack_start (GTK_BOX (hbox14), label74, FALSE, FALSE, 0);

  btn_inscrit = gtk_button_new ();
  gtk_widget_show (btn_inscrit);
  gtk_fixed_put (GTK_FIXED (fixed8), btn_inscrit, 392, 600);
  gtk_widget_set_size_request (btn_inscrit, 200, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (btn_inscrit), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label73 = gtk_label_new_with_mnemonic (_("s'inscrire"));
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (hbox13), label73, FALSE, FALSE, 0);

  alignment41 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment41);
  gtk_fixed_put (GTK_FIXED (fixed8), alignment41, 320, 472);
  gtk_widget_set_size_request (alignment41, 189, 29);

  com_jour_ins = gtk_combo_box_entry_new_text ();
  gtk_widget_show (com_jour_ins);
  gtk_container_add (GTK_CONTAINER (alignment41), com_jour_ins);
  gtk_widget_set_size_request (com_jour_ins, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_ins), _("Lundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_ins), _("Mardi "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_ins), _("Mercredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_ins), _("Jeudi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_ins), _("Vendredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_ins), _("Samdi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_ins), _("Dimanche"));

  alignment44 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment44);
  gtk_fixed_put (GTK_FIXED (fixed8), alignment44, 320, 400);
  gtk_widget_set_size_request (alignment44, 189, 29);

  com_choix_eq_ins = gtk_combo_box_entry_new_text ();
  gtk_widget_show (com_choix_eq_ins);
  gtk_container_add (GTK_CONTAINER (alignment44), com_choix_eq_ins);
  gtk_widget_set_size_request (com_choix_eq_ins, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_choix_eq_ins), _("Barre+disques"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_choix_eq_ins), _("Tapis de course"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_choix_eq_ins), _("Tapis de yoga"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_choix_eq_ins), _("Gants de box"));

  label67 = gtk_label_new (_("<span weight=\"bold\" foreground=\"black\" size=\"large\">Inscription \303\240 un cours sportif</span>"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed8), label67, 240, 16);
  gtk_widget_set_size_request (label67, 320, 48);
  gtk_label_set_use_markup (GTK_LABEL (label67), TRUE);

  label72 = gtk_label_new (_("<b>Choix de cours sportif</b>"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed8), label72, 304, 280);
  gtk_widget_set_size_request (label72, 192, 24);
  gtk_label_set_use_markup (GTK_LABEL (label72), TRUE);

  label198 = gtk_label_new (_("<b>Choix des \303\251quipements</b>"));
  gtk_widget_show (label198);
  gtk_fixed_put (GTK_FIXED (fixed8), label198, 312, 360);
  gtk_widget_set_size_request (label198, 192, 24);
  gtk_label_set_use_markup (GTK_LABEL (label198), TRUE);

  label201 = gtk_label_new (_("<b>Pour Le jour</b>"));
  gtk_widget_show (label201);
  gtk_fixed_put (GTK_FIXED (fixed8), label201, 328, 440);
  gtk_widget_set_size_request (label201, 144, 24);
  gtk_label_set_use_markup (GTK_LABEL (label201), TRUE);

  label202 = gtk_label_new (_("<b>L'Heure de :</b>"));
  gtk_widget_show (label202);
  gtk_fixed_put (GTK_FIXED (fixed8), label202, 240, 536);
  gtk_widget_set_size_request (label202, 128, 24);
  gtk_label_set_use_markup (GTK_LABEL (label202), TRUE);

  label203 = gtk_label_new (_("<b>A</b>"));
  gtk_widget_show (label203);
  gtk_fixed_put (GTK_FIXED (fixed8), label203, 408, 544);
  gtk_widget_set_size_request (label203, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label203), TRUE);

  label129 = gtk_label_new (_("<b>Vos cours dont vous \303\252tes d\303\251j\303\240 inscrit :</b>"));
  gtk_widget_show (label129);
  gtk_fixed_put (GTK_FIXED (fixed8), label129, 272, 80);
  gtk_widget_set_size_request (label129, 272, 24);
  gtk_label_set_use_markup (GTK_LABEL (label129), TRUE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed8), scrolledwindow1, 280, 120);
  gtk_widget_set_size_request (scrolledwindow1, 264, 152);

  treeview_cours = gtk_tree_view_new ();
  gtk_widget_show (treeview_cours);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview_cours);

  alignment45 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment45);
  gtk_fixed_put (GTK_FIXED (fixed8), alignment45, 320, 320);
  gtk_widget_set_size_request (alignment45, 189, 29);

  com_cours_ins = gtk_combo_box_entry_new_text ();
  gtk_widget_show (com_cours_ins);
  gtk_container_add (GTK_CONTAINER (alignment45), com_cours_ins);
  gtk_widget_set_size_request (com_cours_ins, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_cours_ins), _("musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_cours_ins), _("yoga"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_cours_ins), _("box"));

  g_signal_connect ((gpointer) btn_annule_inscrit, "clicked",
                    G_CALLBACK (on_btn_annule_inscrit_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_inscrit, "clicked",
                    G_CALLBACK (on_btn_inscrit_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_cours, "row_activated",
                    G_CALLBACK (on_treeview_cours_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (inscription_window, inscription_window, "inscription_window");
  GLADE_HOOKUP_OBJECT (inscription_window, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (inscription_window, spin_hd_ins, "spin_hd_ins");
  GLADE_HOOKUP_OBJECT (inscription_window, spin_ha_ins, "spin_ha_ins");
  GLADE_HOOKUP_OBJECT (inscription_window, image29, "image29");
  GLADE_HOOKUP_OBJECT (inscription_window, btn_annule_inscrit, "btn_annule_inscrit");
  GLADE_HOOKUP_OBJECT (inscription_window, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (inscription_window, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (inscription_window, image14, "image14");
  GLADE_HOOKUP_OBJECT (inscription_window, label74, "label74");
  GLADE_HOOKUP_OBJECT (inscription_window, btn_inscrit, "btn_inscrit");
  GLADE_HOOKUP_OBJECT (inscription_window, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (inscription_window, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (inscription_window, image13, "image13");
  GLADE_HOOKUP_OBJECT (inscription_window, label73, "label73");
  GLADE_HOOKUP_OBJECT (inscription_window, alignment41, "alignment41");
  GLADE_HOOKUP_OBJECT (inscription_window, com_jour_ins, "com_jour_ins");
  GLADE_HOOKUP_OBJECT (inscription_window, alignment44, "alignment44");
  GLADE_HOOKUP_OBJECT (inscription_window, com_choix_eq_ins, "com_choix_eq_ins");
  GLADE_HOOKUP_OBJECT (inscription_window, label67, "label67");
  GLADE_HOOKUP_OBJECT (inscription_window, label72, "label72");
  GLADE_HOOKUP_OBJECT (inscription_window, label198, "label198");
  GLADE_HOOKUP_OBJECT (inscription_window, label201, "label201");
  GLADE_HOOKUP_OBJECT (inscription_window, label202, "label202");
  GLADE_HOOKUP_OBJECT (inscription_window, label203, "label203");
  GLADE_HOOKUP_OBJECT (inscription_window, label129, "label129");
  GLADE_HOOKUP_OBJECT (inscription_window, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (inscription_window, treeview_cours, "treeview_cours");
  GLADE_HOOKUP_OBJECT (inscription_window, alignment45, "alignment45");
  GLADE_HOOKUP_OBJECT (inscription_window, com_cours_ins, "com_cours_ins");

  return inscription_window;
}

GtkWidget*
create_supp_window (void)
{
  GtkWidget *supp_window;
  GtkWidget *fixed7;
  GtkWidget *entry_ID_En_supp;
  GtkWidget *label84;
  GtkWidget *btn_supp;
  GtkWidget *alignment31;
  GtkWidget *hbox31;
  GtkWidget *image38;
  GtkWidget *label233;
  GtkWidget *btn_retour_supp;
  GtkWidget *image39;
  GtkWidget *label68;

  supp_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (supp_window, 800, 600);
  GTK_WIDGET_SET_FLAGS (supp_window, GTK_CAN_DEFAULT);
  gtk_window_set_title (GTK_WINDOW (supp_window), _("Supprimer un entraineur"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (supp_window), fixed7);

  entry_ID_En_supp = gtk_entry_new ();
  gtk_widget_show (entry_ID_En_supp);
  gtk_fixed_put (GTK_FIXED (fixed7), entry_ID_En_supp, 384, 176);
  gtk_widget_set_size_request (entry_ID_En_supp, 240, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_ID_En_supp), 8226);

  label84 = gtk_label_new (_("ID Entraineur"));
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed7), label84, 224, 184);
  gtk_widget_set_size_request (label84, 112, 16);

  btn_supp = gtk_button_new ();
  gtk_widget_show (btn_supp);
  gtk_fixed_put (GTK_FIXED (fixed7), btn_supp, 304, 304);
  gtk_widget_set_size_request (btn_supp, 224, 40);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (btn_supp), alignment31);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox31);

  image38 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image38);
  gtk_box_pack_start (GTK_BOX (hbox31), image38, FALSE, FALSE, 0);

  label233 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label233);
  gtk_box_pack_start (GTK_BOX (hbox31), label233, FALSE, FALSE, 0);

  btn_retour_supp = gtk_button_new ();
  gtk_widget_show (btn_retour_supp);
  gtk_fixed_put (GTK_FIXED (fixed7), btn_retour_supp, 40, 48);
  gtk_widget_set_size_request (btn_retour_supp, 56, 40);

  image39 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image39);
  gtk_container_add (GTK_CONTAINER (btn_retour_supp), image39);

  label68 = gtk_label_new (_("<span weight=\"bold\" foreground=\"black\" size=\"large\">Supprimer un entraineur</span>"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed7), label68, 280, 48);
  gtk_widget_set_size_request (label68, 280, 40);
  gtk_label_set_use_markup (GTK_LABEL (label68), TRUE);

  g_signal_connect ((gpointer) btn_supp, "clicked",
                    G_CALLBACK (on_btn_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_retour_supp, "clicked",
                    G_CALLBACK (on_btn_retour_supp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supp_window, supp_window, "supp_window");
  GLADE_HOOKUP_OBJECT (supp_window, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (supp_window, entry_ID_En_supp, "entry_ID_En_supp");
  GLADE_HOOKUP_OBJECT (supp_window, label84, "label84");
  GLADE_HOOKUP_OBJECT (supp_window, btn_supp, "btn_supp");
  GLADE_HOOKUP_OBJECT (supp_window, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (supp_window, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (supp_window, image38, "image38");
  GLADE_HOOKUP_OBJECT (supp_window, label233, "label233");
  GLADE_HOOKUP_OBJECT (supp_window, btn_retour_supp, "btn_retour_supp");
  GLADE_HOOKUP_OBJECT (supp_window, image39, "image39");
  GLADE_HOOKUP_OBJECT (supp_window, label68, "label68");

  return supp_window;
}

GtkWidget*
create_Login_entraineur (void)
{
  GtkWidget *Login_entraineur;
  GtkWidget *fixed10;
  GtkWidget *entry_ID_EN_cnx;
  GtkWidget *entry_mdp_EN_cnx;
  GtkWidget *label131;
  GtkWidget *label132;
  GtkWidget *label136;
  GtkWidget *btn_annule_cnx;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label134;
  GtkWidget *btn_cnx_en;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label135;

  Login_entraineur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Login_entraineur, 800, 600);
  GTK_WIDGET_SET_FLAGS (Login_entraineur, GTK_CAN_DEFAULT);
  gtk_window_set_title (GTK_WINDOW (Login_entraineur), _("Se connecter Entraineur"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (Login_entraineur), fixed10);

  entry_ID_EN_cnx = gtk_entry_new ();
  gtk_widget_show (entry_ID_EN_cnx);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_ID_EN_cnx, 408, 144);
  gtk_widget_set_size_request (entry_ID_EN_cnx, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_ID_EN_cnx), 8226);

  entry_mdp_EN_cnx = gtk_entry_new ();
  gtk_widget_show (entry_mdp_EN_cnx);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_mdp_EN_cnx, 408, 200);
  gtk_widget_set_size_request (entry_mdp_EN_cnx, 216, 32);
  gtk_entry_set_visibility (GTK_ENTRY (entry_mdp_EN_cnx), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mdp_EN_cnx), 8226);

  label131 = gtk_label_new (_("Id Entraineur"));
  gtk_widget_show (label131);
  gtk_fixed_put (GTK_FIXED (fixed10), label131, 216, 152);
  gtk_widget_set_size_request (label131, 144, 24);

  label132 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label132);
  gtk_fixed_put (GTK_FIXED (fixed10), label132, 232, 208);
  gtk_widget_set_size_request (label132, 120, 16);

  label136 = gtk_label_new (_("<span weight=\"bold\" foreground=\"black\" size=\"large\">Informations de connexion</span>"));
  gtk_widget_show (label136);
  gtk_fixed_put (GTK_FIXED (fixed10), label136, 280, 48);
  gtk_widget_set_size_request (label136, 288, 40);
  gtk_label_set_use_markup (GTK_LABEL (label136), TRUE);

  btn_annule_cnx = gtk_button_new ();
  gtk_widget_show (btn_annule_cnx);
  gtk_fixed_put (GTK_FIXED (fixed10), btn_annule_cnx, 248, 336);
  gtk_widget_set_size_request (btn_annule_cnx, 152, 32);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (btn_annule_cnx), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label134 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label134);
  gtk_box_pack_start (GTK_BOX (hbox20), label134, FALSE, FALSE, 0);

  btn_cnx_en = gtk_button_new ();
  gtk_widget_show (btn_cnx_en);
  gtk_fixed_put (GTK_FIXED (fixed10), btn_cnx_en, 424, 336);
  gtk_widget_set_size_request (btn_cnx_en, 160, 32);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (btn_cnx_en), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label135 = gtk_label_new_with_mnemonic (_("Se connecter"));
  gtk_widget_show (label135);
  gtk_box_pack_start (GTK_BOX (hbox21), label135, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) btn_annule_cnx, "clicked",
                    G_CALLBACK (on_btn_annule_cnx_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_cnx_en, "clicked",
                    G_CALLBACK (on_btn_cnx_en_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Login_entraineur, Login_entraineur, "Login_entraineur");
  GLADE_HOOKUP_OBJECT (Login_entraineur, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (Login_entraineur, entry_ID_EN_cnx, "entry_ID_EN_cnx");
  GLADE_HOOKUP_OBJECT (Login_entraineur, entry_mdp_EN_cnx, "entry_mdp_EN_cnx");
  GLADE_HOOKUP_OBJECT (Login_entraineur, label131, "label131");
  GLADE_HOOKUP_OBJECT (Login_entraineur, label132, "label132");
  GLADE_HOOKUP_OBJECT (Login_entraineur, label136, "label136");
  GLADE_HOOKUP_OBJECT (Login_entraineur, btn_annule_cnx, "btn_annule_cnx");
  GLADE_HOOKUP_OBJECT (Login_entraineur, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (Login_entraineur, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (Login_entraineur, image20, "image20");
  GLADE_HOOKUP_OBJECT (Login_entraineur, label134, "label134");
  GLADE_HOOKUP_OBJECT (Login_entraineur, btn_cnx_en, "btn_cnx_en");
  GLADE_HOOKUP_OBJECT (Login_entraineur, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (Login_entraineur, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (Login_entraineur, image21, "image21");
  GLADE_HOOKUP_OBJECT (Login_entraineur, label135, "label135");

  return Login_entraineur;
}

GtkWidget*
create_Ajouter_window (void)
{
  GtkWidget *Ajouter_window;
  GtkWidget *fixed11;
  GtkWidget *entry_id_en_aj;
  GtkWidget *entry_nom_aj;
  GtkWidget *entry_prenom_aj;
  GtkWidget *entry_num_aj;
  GtkWidget *entry_email_aj;
  GtkObject *spin_hd_aj_adj;
  GtkWidget *spin_hd_aj;
  GtkObject *spin_hf_aj_adj;
  GtkWidget *spin_hf_aj;
  GtkWidget *radio_femme_aj;
  GSList *radio_femme_aj_group = NULL;
  GtkWidget *radio_homme_aj;
  GtkWidget *alignment40;
  GtkWidget *com_specialite_aj;
  GtkWidget *entry_mdp_aj;
  GtkWidget *btn_annule_aj;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label177;
  GtkWidget *btn_ajoute_en;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label176;
  GtkWidget *label234;
  GtkWidget *label169;
  GtkWidget *label168;
  GtkWidget *label167;
  GtkWidget *label165;
  GtkWidget *label164;
  GtkWidget *label163;
  GtkWidget *label162;
  GtkWidget *label166;
  GtkWidget *label200;
  GtkWidget *label175;
  GtkWidget *label174;
  GtkWidget *label172;
  GtkWidget *check_oui_aj;
  GtkWidget *check_non__aj;
  GtkWidget *com_jour_aj;
  GtkWidget *com_center_aj;
  GtkWidget *label238;
  GtkWidget *label173;

  Ajouter_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajouter_window), _("Ajouter un entraineur"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (Ajouter_window), fixed11);
  gtk_widget_set_size_request (fixed11, 800, 650);
  GTK_WIDGET_SET_FLAGS (fixed11, GTK_CAN_DEFAULT);

  entry_id_en_aj = gtk_entry_new ();
  gtk_widget_show (entry_id_en_aj);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_id_en_aj, 288, 72);
  gtk_widget_set_size_request (entry_id_en_aj, 240, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_en_aj), 8226);

  entry_nom_aj = gtk_entry_new ();
  gtk_widget_show (entry_nom_aj);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_nom_aj, 288, 104);
  gtk_widget_set_size_request (entry_nom_aj, 240, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom_aj), 8226);

  entry_prenom_aj = gtk_entry_new ();
  gtk_widget_show (entry_prenom_aj);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_prenom_aj, 288, 136);
  gtk_widget_set_size_request (entry_prenom_aj, 240, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom_aj), 8226);

  entry_num_aj = gtk_entry_new ();
  gtk_widget_show (entry_num_aj);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_num_aj, 288, 200);
  gtk_widget_set_size_request (entry_num_aj, 240, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_num_aj), 8226);

  entry_email_aj = gtk_entry_new ();
  gtk_widget_show (entry_email_aj);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_email_aj, 288, 264);
  gtk_widget_set_size_request (entry_email_aj, 240, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_email_aj), 8226);

  spin_hd_aj_adj = gtk_adjustment_new (0, 0, 100, 1, 0, 0);
  spin_hd_aj = gtk_spin_button_new (GTK_ADJUSTMENT (spin_hd_aj_adj), 1, 0);
  gtk_widget_show (spin_hd_aj);
  gtk_fixed_put (GTK_FIXED (fixed11), spin_hd_aj, 336, 456);
  gtk_widget_set_size_request (spin_hd_aj, 60, 27);

  spin_hf_aj_adj = gtk_adjustment_new (0, 0, 100, 1, 0, 0);
  spin_hf_aj = gtk_spin_button_new (GTK_ADJUSTMENT (spin_hf_aj_adj), 1, 0);
  gtk_widget_show (spin_hf_aj);
  gtk_fixed_put (GTK_FIXED (fixed11), spin_hf_aj, 336, 488);
  gtk_widget_set_size_request (spin_hf_aj, 60, 27);

  radio_femme_aj = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radio_femme_aj);
  gtk_fixed_put (GTK_FIXED (fixed11), radio_femme_aj, 416, 168);
  gtk_widget_set_size_request (radio_femme_aj, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_femme_aj), radio_femme_aj_group);
  radio_femme_aj_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_femme_aj));

  radio_homme_aj = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radio_homme_aj);
  gtk_fixed_put (GTK_FIXED (fixed11), radio_homme_aj, 296, 168);
  gtk_widget_set_size_request (radio_homme_aj, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_homme_aj), radio_femme_aj_group);
  radio_femme_aj_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_homme_aj));

  alignment40 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment40);
  gtk_fixed_put (GTK_FIXED (fixed11), alignment40, 288, 232);
  gtk_widget_set_size_request (alignment40, 189, 29);

  com_specialite_aj = gtk_combo_box_entry_new_text ();
  gtk_widget_show (com_specialite_aj);
  gtk_container_add (GTK_CONTAINER (alignment40), com_specialite_aj);
  gtk_widget_set_size_request (com_specialite_aj, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_specialite_aj), _("Musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_specialite_aj), _("Cardio Training"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_specialite_aj), _("Yoga"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_specialite_aj), _("Box"));

  entry_mdp_aj = gtk_entry_new ();
  gtk_widget_show (entry_mdp_aj);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_mdp_aj, 288, 296);
  gtk_widget_set_size_request (entry_mdp_aj, 240, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mdp_aj), 8226);

  btn_annule_aj = gtk_button_new ();
  gtk_widget_show (btn_annule_aj);
  gtk_fixed_put (GTK_FIXED (fixed11), btn_annule_aj, 176, 608);
  gtk_widget_set_size_request (btn_annule_aj, 208, 40);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (btn_annule_aj), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label177 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label177);
  gtk_box_pack_start (GTK_BOX (hbox24), label177, FALSE, FALSE, 0);

  btn_ajoute_en = gtk_button_new ();
  gtk_widget_show (btn_ajoute_en);
  gtk_fixed_put (GTK_FIXED (fixed11), btn_ajoute_en, 440, 608);
  gtk_widget_set_size_request (btn_ajoute_en, 208, 40);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (btn_ajoute_en), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label176 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label176);
  gtk_box_pack_start (GTK_BOX (hbox23), label176, FALSE, FALSE, 0);

  label234 = gtk_label_new (_("<b>Mot de passe</b>"));
  gtk_widget_show (label234);
  gtk_fixed_put (GTK_FIXED (fixed11), label234, 88, 296);
  gtk_widget_set_size_request (label234, 144, 24);
  gtk_label_set_use_markup (GTK_LABEL (label234), TRUE);

  label169 = gtk_label_new (_("<b>Adresse email</b>"));
  gtk_widget_show (label169);
  gtk_fixed_put (GTK_FIXED (fixed11), label169, 104, 272);
  gtk_widget_set_size_request (label169, 120, 16);
  gtk_label_set_use_markup (GTK_LABEL (label169), TRUE);

  label168 = gtk_label_new (_("<b>Sp\303\251cialit\303\251</b>"));
  gtk_widget_show (label168);
  gtk_fixed_put (GTK_FIXED (fixed11), label168, 104, 240);
  gtk_widget_set_size_request (label168, 96, 16);
  gtk_label_set_use_markup (GTK_LABEL (label168), TRUE);

  label167 = gtk_label_new (_("<b>Num\303\251ro T\303\251l</b>"));
  gtk_widget_show (label167);
  gtk_fixed_put (GTK_FIXED (fixed11), label167, 104, 200);
  gtk_widget_set_size_request (label167, 112, 24);
  gtk_label_set_use_markup (GTK_LABEL (label167), TRUE);

  label165 = gtk_label_new (_("<b>Sexe</b>"));
  gtk_widget_show (label165);
  gtk_fixed_put (GTK_FIXED (fixed11), label165, 104, 176);
  gtk_widget_set_size_request (label165, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label165), TRUE);

  label164 = gtk_label_new (_("<b>Pr\303\251nom</b>"));
  gtk_widget_show (label164);
  gtk_fixed_put (GTK_FIXED (fixed11), label164, 96, 144);
  gtk_widget_set_size_request (label164, 88, 16);
  gtk_label_set_use_markup (GTK_LABEL (label164), TRUE);

  label163 = gtk_label_new (_("<b>Nom</b>"));
  gtk_widget_show (label163);
  gtk_fixed_put (GTK_FIXED (fixed11), label163, 104, 112);
  gtk_widget_set_size_request (label163, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label163), TRUE);

  label162 = gtk_label_new (_("<b>ID entraineur</b>"));
  gtk_widget_show (label162);
  gtk_fixed_put (GTK_FIXED (fixed11), label162, 96, 80);
  gtk_widget_set_size_request (label162, 128, 24);
  gtk_label_set_use_markup (GTK_LABEL (label162), TRUE);

  label166 = gtk_label_new (_("<span weight=\"bold\" foreground=\"black\" size=\"large\">Ajouter un entraineur</span>"));
  gtk_widget_show (label166);
  gtk_fixed_put (GTK_FIXED (fixed11), label166, 224, 8);
  gtk_widget_set_size_request (label166, 336, 40);
  gtk_label_set_use_markup (GTK_LABEL (label166), TRUE);

  label200 = gtk_label_new (_("<b>Priv\303\251 :</b>"));
  gtk_widget_show (label200);
  gtk_fixed_put (GTK_FIXED (fixed11), label200, 96, 528);
  gtk_widget_set_size_request (label200, 88, 16);
  gtk_label_set_use_markup (GTK_LABEL (label200), TRUE);

  label175 = gtk_label_new (_("<b>Heure fin :</b>"));
  gtk_widget_show (label175);
  gtk_fixed_put (GTK_FIXED (fixed11), label175, 112, 496);
  gtk_widget_set_size_request (label175, 88, 16);
  gtk_label_set_use_markup (GTK_LABEL (label175), TRUE);

  label174 = gtk_label_new (_("<b>Heure de d\303\251but :</b>"));
  gtk_widget_show (label174);
  gtk_fixed_put (GTK_FIXED (fixed11), label174, 104, 464);
  gtk_widget_set_size_request (label174, 136, 16);
  gtk_label_set_use_markup (GTK_LABEL (label174), TRUE);

  label172 = gtk_label_new (_("<b>Au centre sportif :</b>"));
  gtk_widget_show (label172);
  gtk_fixed_put (GTK_FIXED (fixed11), label172, 104, 384);
  gtk_widget_set_size_request (label172, 136, 24);
  gtk_label_set_use_markup (GTK_LABEL (label172), TRUE);

  check_oui_aj = gtk_check_button_new_with_mnemonic (_("OUI"));
  gtk_widget_show (check_oui_aj);
  gtk_fixed_put (GTK_FIXED (fixed11), check_oui_aj, 288, 528);
  gtk_widget_set_size_request (check_oui_aj, 134, 24);

  check_non__aj = gtk_check_button_new_with_mnemonic (_("NON"));
  gtk_widget_show (check_non__aj);
  gtk_fixed_put (GTK_FIXED (fixed11), check_non__aj, 408, 528);
  gtk_widget_set_size_request (check_non__aj, 134, 24);

  com_jour_aj = gtk_combo_box_entry_new_text ();
  gtk_widget_show (com_jour_aj);
  gtk_fixed_put (GTK_FIXED (fixed11), com_jour_aj, 296, 424);
  gtk_widget_set_size_request (com_jour_aj, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_aj), _("Lundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_aj), _("Mardi "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_aj), _("Mercredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_aj), _("Jeudi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_aj), _("Vendredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_aj), _("Samdi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_jour_aj), _("Dimanche"));

  com_center_aj = gtk_combo_box_entry_new_text ();
  gtk_widget_show (com_center_aj);
  gtk_fixed_put (GTK_FIXED (fixed11), com_center_aj, 296, 384);
  gtk_widget_set_size_request (com_center_aj, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_center_aj), _("Centre 1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_center_aj), _("centre 2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_center_aj), _("centre 3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (com_center_aj), _("centre 4"));

  label238 = gtk_label_new (_("<b>D\303\251sponibilit\303\251 de l'entraineurs </b>"));
  gtk_widget_show (label238);
  gtk_fixed_put (GTK_FIXED (fixed11), label238, 40, 344);
  gtk_widget_set_size_request (label238, 336, 16);
  gtk_label_set_use_markup (GTK_LABEL (label238), TRUE);

  label173 = gtk_label_new (_("<b>Le Jour :</b>"));
  gtk_widget_show (label173);
  gtk_fixed_put (GTK_FIXED (fixed11), label173, 104, 424);
  gtk_widget_set_size_request (label173, 88, 16);
  gtk_label_set_use_markup (GTK_LABEL (label173), TRUE);

  g_signal_connect ((gpointer) radio_femme_aj, "toggled",
                    G_CALLBACK (on_radio_femme_aj_toggled),
                    NULL);
  g_signal_connect ((gpointer) radio_homme_aj, "toggled",
                    G_CALLBACK (on_radio_homme_aj_toggled),
                    NULL);
  g_signal_connect ((gpointer) btn_annule_aj, "clicked",
                    G_CALLBACK (on_btn_annule_aj_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_ajoute_en, "clicked",
                    G_CALLBACK (on_btn_ajoute_en_clicked),
                    NULL);
  g_signal_connect ((gpointer) check_oui_aj, "toggled",
                    G_CALLBACK (on_check_oui_aj_toggled),
                    NULL);
  g_signal_connect ((gpointer) check_non__aj, "toggled",
                    G_CALLBACK (on_check_non__aj_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter_window, Ajouter_window, "Ajouter_window");
  GLADE_HOOKUP_OBJECT (Ajouter_window, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (Ajouter_window, entry_id_en_aj, "entry_id_en_aj");
  GLADE_HOOKUP_OBJECT (Ajouter_window, entry_nom_aj, "entry_nom_aj");
  GLADE_HOOKUP_OBJECT (Ajouter_window, entry_prenom_aj, "entry_prenom_aj");
  GLADE_HOOKUP_OBJECT (Ajouter_window, entry_num_aj, "entry_num_aj");
  GLADE_HOOKUP_OBJECT (Ajouter_window, entry_email_aj, "entry_email_aj");
  GLADE_HOOKUP_OBJECT (Ajouter_window, spin_hd_aj, "spin_hd_aj");
  GLADE_HOOKUP_OBJECT (Ajouter_window, spin_hf_aj, "spin_hf_aj");
  GLADE_HOOKUP_OBJECT (Ajouter_window, radio_femme_aj, "radio_femme_aj");
  GLADE_HOOKUP_OBJECT (Ajouter_window, radio_homme_aj, "radio_homme_aj");
  GLADE_HOOKUP_OBJECT (Ajouter_window, alignment40, "alignment40");
  GLADE_HOOKUP_OBJECT (Ajouter_window, com_specialite_aj, "com_specialite_aj");
  GLADE_HOOKUP_OBJECT (Ajouter_window, entry_mdp_aj, "entry_mdp_aj");
  GLADE_HOOKUP_OBJECT (Ajouter_window, btn_annule_aj, "btn_annule_aj");
  GLADE_HOOKUP_OBJECT (Ajouter_window, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (Ajouter_window, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (Ajouter_window, image24, "image24");
  GLADE_HOOKUP_OBJECT (Ajouter_window, label177, "label177");
  GLADE_HOOKUP_OBJECT (Ajouter_window, btn_ajoute_en, "btn_ajoute_en");
  GLADE_HOOKUP_OBJECT (Ajouter_window, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (Ajouter_window, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (Ajouter_window, image23, "image23");
  GLADE_HOOKUP_OBJECT (Ajouter_window, label176, "label176");
  GLADE_HOOKUP_OBJECT (Ajouter_window, label234, "label234");
  GLADE_HOOKUP_OBJECT (Ajouter_window, label169, "label169");
  GLADE_HOOKUP_OBJECT (Ajouter_window, label168, "label168");
  GLADE_HOOKUP_OBJECT (Ajouter_window, label167, "label167");
  GLADE_HOOKUP_OBJECT (Ajouter_window, label165, "label165");
  GLADE_HOOKUP_OBJECT (Ajouter_window, label164, "label164");
  GLADE_HOOKUP_OBJECT (Ajouter_window, label163, "label163");
  GLADE_HOOKUP_OBJECT (Ajouter_window, label162, "label162");
  GLADE_HOOKUP_OBJECT (Ajouter_window, label166, "label166");
  GLADE_HOOKUP_OBJECT (Ajouter_window, label200, "label200");
  GLADE_HOOKUP_OBJECT (Ajouter_window, label175, "label175");
  GLADE_HOOKUP_OBJECT (Ajouter_window, label174, "label174");
  GLADE_HOOKUP_OBJECT (Ajouter_window, label172, "label172");
  GLADE_HOOKUP_OBJECT (Ajouter_window, check_oui_aj, "check_oui_aj");
  GLADE_HOOKUP_OBJECT (Ajouter_window, check_non__aj, "check_non__aj");
  GLADE_HOOKUP_OBJECT (Ajouter_window, com_jour_aj, "com_jour_aj");
  GLADE_HOOKUP_OBJECT (Ajouter_window, com_center_aj, "com_center_aj");
  GLADE_HOOKUP_OBJECT (Ajouter_window, label238, "label238");
  GLADE_HOOKUP_OBJECT (Ajouter_window, label173, "label173");

  return Ajouter_window;
}

GtkWidget*
create_liste_entraineurs_window (void)
{
  GtkWidget *liste_entraineurs_window;
  GtkWidget *fixed12;
  GtkWidget *scrolled_entraineurs;
  GtkWidget *treeview_entraineurs;
  GtkWidget *btn_actualiser_entraineurs;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image25;
  GtkWidget *label223;
  GtkWidget *_;
  GtkWidget *btn_retour_l_en;
  GtkWidget *image37;

  liste_entraineurs_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (liste_entraineurs_window, 800, 600);
  GTK_WIDGET_SET_FLAGS (liste_entraineurs_window, GTK_CAN_DEFAULT);
  gtk_window_set_title (GTK_WINDOW (liste_entraineurs_window), _("liste_entraineurs_window"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (liste_entraineurs_window), fixed12);

  scrolled_entraineurs = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolled_entraineurs);
  gtk_fixed_put (GTK_FIXED (fixed12), scrolled_entraineurs, 184, 128);
  gtk_widget_set_size_request (scrolled_entraineurs, 496, 352);

  treeview_entraineurs = gtk_tree_view_new ();
  gtk_widget_show (treeview_entraineurs);
  gtk_container_add (GTK_CONTAINER (scrolled_entraineurs), treeview_entraineurs);

  btn_actualiser_entraineurs = gtk_button_new ();
  gtk_widget_show (btn_actualiser_entraineurs);
  gtk_fixed_put (GTK_FIXED (fixed12), btn_actualiser_entraineurs, 264, 512);
  gtk_widget_set_size_request (btn_actualiser_entraineurs, 304, 32);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (btn_actualiser_entraineurs), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image25 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox25), image25, FALSE, FALSE, 0);

  label223 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label223);
  gtk_box_pack_start (GTK_BOX (hbox25), label223, FALSE, FALSE, 0);

  _ = gtk_label_new (_("<span weight=\"bold\" foreground=\"black\" size=\"large\">Liste des entraineurs</span>"));
  gtk_widget_show (_);
  gtk_fixed_put (GTK_FIXED (fixed12), _, 256, 32);
  gtk_widget_set_size_request (_, 320, 40);
  gtk_label_set_use_markup (GTK_LABEL (_), TRUE);

  btn_retour_l_en = gtk_button_new ();
  gtk_widget_show (btn_retour_l_en);
  gtk_fixed_put (GTK_FIXED (fixed12), btn_retour_l_en, 24, 32);
  gtk_widget_set_size_request (btn_retour_l_en, 56, 40);

  image37 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image37);
  gtk_container_add (GTK_CONTAINER (btn_retour_l_en), image37);

  g_signal_connect ((gpointer) treeview_entraineurs, "row_activated",
                    G_CALLBACK (on_treeview_entraineurs_row_activated),
                    NULL);
  g_signal_connect ((gpointer) btn_actualiser_entraineurs, "clicked",
                    G_CALLBACK (on_btn_actualiser_entraineurs_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_retour_l_en, "clicked",
                    G_CALLBACK (on_btn_retour_l_en_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (liste_entraineurs_window, liste_entraineurs_window, "liste_entraineurs_window");
  GLADE_HOOKUP_OBJECT (liste_entraineurs_window, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (liste_entraineurs_window, scrolled_entraineurs, "scrolled_entraineurs");
  GLADE_HOOKUP_OBJECT (liste_entraineurs_window, treeview_entraineurs, "treeview_entraineurs");
  GLADE_HOOKUP_OBJECT (liste_entraineurs_window, btn_actualiser_entraineurs, "btn_actualiser_entraineurs");
  GLADE_HOOKUP_OBJECT (liste_entraineurs_window, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (liste_entraineurs_window, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (liste_entraineurs_window, image25, "image25");
  GLADE_HOOKUP_OBJECT (liste_entraineurs_window, label223, "label223");
  GLADE_HOOKUP_OBJECT (liste_entraineurs_window, _, "_");
  GLADE_HOOKUP_OBJECT (liste_entraineurs_window, btn_retour_l_en, "btn_retour_l_en");
  GLADE_HOOKUP_OBJECT (liste_entraineurs_window, image37, "image37");

  return liste_entraineurs_window;
}

