/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_admin_window (void);
GtkWidget* create_gesen_window (void);
GtkWidget* create_modifier_window (void);
GtkWidget* create_Login_admin (void);
GtkWidget* create_recherche_window (void);
GtkWidget* create_inscription_window (void);
GtkWidget* create_supp_window (void);
GtkWidget* create_Login_entraineur (void);
GtkWidget* create_Ajouter_window (void);
GtkWidget* create_liste_entraineurs_window (void);
