/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "gestion_entraineurs.h"
#include "inscription.h"

int
main (int argc, char *argv[])
{
  GtkWidget *gesen_window;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /* Charger les données des entraineurs */
  charger_entraineurs();
  charger_inscriptions();

  /* Afficher seulement la fenêtre principale */
  gesen_window = create_gesen_window ();
  gtk_widget_show (gesen_window);

  gtk_main ();
  return 0;
}
